apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: hello
  name: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: hello
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose --file docker-compose.yml convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: hello
    spec:
      containers:
        - env:
            - name: ENVIRONMENT_NAME
              value: local
            - name: MONGODB_CONECTION_URL
              value: mongodb://root:example@mongo:27017/
          image: robertpoziumschi/hello-img-pipeline:v1.1.0
          name: hello
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
