apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    hello-service: hello
  name: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      hello-service: hello
  strategy: {}
  template:
    metadata:
      labels:
        hello-service: hello
    spec:
      containers:
        - env:
            - name: ENVIRONMENT_NAME
              value: local
            - name: MONGODB_CONECTION_URL
              value: mongodb://root:example@mongo:27017/
          image: robertpoziumschi/hello-img-pipeline:v1.1.0
          name: hello
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
