apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    mongo-service: mongo
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      mongo-service: mongo
  strategy: {}
  template:
    metadata:
      labels:
        mongo-service: mongo
    spec:
      containers:
        - env:
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: example
            - name: MONGO_INITDB_ROOT_USERNAME
              value: root
          image: mongo:5.0.2
          name: mongo
          ports:
            - containerPort: 27017
          resources: {}
      restartPolicy: Always
status: {}
